algorithm: fixmatch
save_dir: ./saved_models/usb_cv/
save_name: fixmatch_supervised
resume: False
load_path: ./saved_models/usb_cv//fixmatch_cifar100_400_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 20
num_train_iter: 200000
num_log_iter: 2000
num_eval_iter: 2000
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 100
num_labels: 5
uratio: 1
ema_m: 0.999
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 0.0
img_size: 224
crop_ratio: 1.0
optim: AdamW
lr: 0.001
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0001
amp: False
clip: 0.0
use_cat: True
net: vit_small_patch16_224
net_from_name: False
data_dir:  /mnt/disk1/mbbank/cuong/Data
dataset: data70k
train_sampler: RandomSampler
num_classes: 5
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10006
dist_backend: nccl
gpu: 0
use_pretrain: True
pretrain_path: /mnt/disk1/mbbank/cuong/Semi-supervised-learning_Image-quality/pretrained_weights/vit_small_patch16_224_mlp_im_1k_224.pth
ema: True