algorithm: fixmatch
save_dir: ./saved_models/usb_cv/
save_name: fixmatch_vit_small_patch16_224_data70k

overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 100
num_train_iter: 1000000
num_log_iter: 2048
num_eval_iter: 2048
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 1024
num_labels: 5
uratio: 1
ema_m: 0.0
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 0.0005
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: vit_small_dinov2
net_from_name: False
data_dir: /mnt/disk1/mbbank/cuong/Data
dataset: sample
train_sampler: RandomSampler
num_classes: 5
num_workers: 4
gpu: 0
world_size: 1
distributed: False
use_pretrain: False
pretrain_path: /mnt/disk1/mbbank/cuong/Semi-supervised-learning_Image-quality/pretrained_weights/vit_small_patch16_224_mlp_im_1k_224.pth