algorithm: freesimmatch
save_dir: ./saved_models/usb_cv/
save_name: freesimmatch
resume: False
load_path: ./saved_models/usb_cv//simmatch_cifar100_200_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 100
num_train_iter: 1000000
num_log_iter: 2048
num_eval_iter: 2048
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 1024
num_labels: 5
uratio: 1
ema_m: 0.999
p_cutoff: 0.95
in_loss_ratio: 1.0
ulb_loss_ratio: 1.0
proj_size: 128
K: 256
da_len: 32
smoothing_alpha: 0.9
T: 0.1
img_size: 32
crop_ratio: 0.875
optim: Lion
lr: 0.0005
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: vit_tiny_patch2_32
net_from_name: False
data_dir:  /mnt/disk1/mbbank/cuong/Data
dataset: sample
train_sampler: RandomSampler
num_classes: 5
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10071
dist_backend: nccl
gpu: 0
use_pretrain: True
pretrain_path: /mnt/disk1/mbbank/cuong/Semi-supervised-learning_Image-quality/pretrained_weights/vit_tiny_patch2_32_mlp_im_1k_32.pth

hard_label: True
ent_loss_ratio: 0.001

