algorithm: freesimmatch
save_dir: ./saved_models/usb_cv/
save_name: freesimmatch_vit_small_patch16_224_data70k_Sophia_4
resume: False
load_path: ./saved_models/usb_cv/freesimmatch_vit_small_patch16_224_data70k_Sophia_4/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 100
num_train_iter: 1000000
num_log_iter: 2048
num_eval_iter: 2048
batch_size: 5
eval_batch_size: 16
num_warmup_iter: 1024
num_labels: 5
uratio: 4
ema_m: 0.999
p_cutoff: 0.95
in_loss_ratio: 1.0
ulb_loss_ratio: 1.0
proj_size: 128
K: 256
da_len: 32
smoothing_alpha: 0.9
T: 0.1
img_size: 224
crop_ratio: 0.875
optim: Sophia
lr: 0.00005
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: vit_small_patch16_224
net_from_name: False
data_dir:  /mnt/disk1/mbbank/cuong/Data
dataset: data70k
train_sampler: RandomSampler
num_classes: 5
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10071
dist_backend: nccl
gpu: 0
use_pretrain: False
pretrain_path: /mnt/disk1/mbbank/cuong/Semi-supervised-learning_Image-quality/pretrained_weights/vit_small_patch16_224_mlp_im_1k_224.pth
ema: True
hard_label: True
ent_loss_ratio: 0.001

